"""Phase 1 핵심 스키마 생성

Revision ID: 21b748d3ce27
Revises:
Create Date: 2026-07-10 23:56:37.621841
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "21b748d3ce27"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("institution_type", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
        sa.UniqueConstraint("name", name=op.f("uq_institutions_name")),
    )
    op.create_table(
        "rule_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rule_type", sa.String(length=80), nullable=False),
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("review_kind", sa.String(length=40), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("reviewer_ref", sa.String(length=120), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_reviews")),
        sa.UniqueConstraint(
            "rule_type",
            "rule_id",
            "review_kind",
            "reviewer_ref",
            name=op.f("uq_rule_reviews_rule_type"),
        ),
    )
    with op.batch_alter_table("rule_reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_reviews_rule_id"), ["rule_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rule_reviews_rule_type"), ["rule_type"], unique=False)

    op.create_table(
        "student_academic_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=120), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("grade", sa.Integer(), nullable=False),
        sa.Column("semester", sa.Integer(), nullable=False),
        sa.Column("record_source", sa.String(length=40), nullable=False),
        sa.Column("original_school_id", sa.String(length=120), nullable=True),
        sa.Column("vocational_institution_name", sa.String(length=200), nullable=True),
        sa.Column("is_vocational_training_semester", sa.Boolean(), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "record_source IN ('HOME_SCHOOL_RECORD', 'VOCATIONAL_TRAINING_RECORD', 'GED_RECORD', 'MANUAL_INPUT')",
            name=op.f("ck_student_academic_records_record_source_valid"),
        ),
        sa.CheckConstraint(
            "grade BETWEEN 1 AND 3", name=op.f("ck_student_academic_records_grade_valid")
        ),
        sa.CheckConstraint(
            "semester BETWEEN 1 AND 2", name=op.f("ck_student_academic_records_semester_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_academic_records")),
        sa.UniqueConstraint(
            "student_id",
            "academic_year",
            "grade",
            "semester",
            "record_source",
            name=op.f("uq_student_academic_records_student_id"),
        ),
    )
    with op.batch_alter_table("student_academic_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_academic_records_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "admission_rounds",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=36), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_admission_rounds_institution_id_institutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_rounds")),
        sa.UniqueConstraint(
            "institution_id",
            "academic_year",
            "code",
            name=op.f("uq_admission_rounds_institution_id"),
        ),
    )
    with op.batch_alter_table("admission_rounds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admission_rounds_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "campuses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("institution_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_campuses_institution_id_institutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campuses")),
        sa.UniqueConstraint("institution_id", "name", name=op.f("uq_campuses_institution_id")),
    )
    with op.batch_alter_table("campuses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_campuses_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "student_course_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("academic_record_id", sa.String(length=36), nullable=False),
        sa.Column("subject_group", sa.String(length=120), nullable=True),
        sa.Column("subject_name", sa.String(length=200), nullable=False),
        sa.Column("credits", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("raw_score", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("course_mean", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("standard_deviation", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("achievement_level", sa.String(length=20), nullable=True),
        sa.Column("enrollment_count", sa.Integer(), nullable=True),
        sa.Column("rank_grade", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("achievement_distribution", sa.JSON(), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("extraction_method", sa.String(length=40), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("user_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_record_id"],
            ["student_academic_records.id"],
            name=op.f("fk_student_course_records_academic_record_id_student_academic_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_course_records")),
    )
    with op.batch_alter_table("student_course_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_course_records_academic_record_id"),
            ["academic_record_id"],
            unique=False,
        )

    op.create_table(
        "vocational_course_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("academic_record_id", sa.String(length=36), nullable=False),
        sa.Column("course_name", sa.String(length=200), nullable=False),
        sa.Column("report_type", sa.String(length=40), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_record_id"],
            ["student_academic_records.id"],
            name=op.f("fk_vocational_course_reports_academic_record_id_student_academic_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocational_course_reports")),
    )
    with op.batch_alter_table("vocational_course_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vocational_course_reports_academic_record_id"),
            ["academic_record_id"],
            unique=False,
        )

    op.create_table(
        "assessment_components",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vocational_course_report_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("maximum_score", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vocational_course_report_id"],
            ["vocational_course_reports.id"],
            name=op.f(
                "fk_assessment_components_vocational_course_report_id_vocational_course_reports"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_components")),
        sa.UniqueConstraint(
            "vocational_course_report_id",
            "name",
            name=op.f("uq_assessment_components_vocational_course_report_id"),
        ),
    )
    with op.batch_alter_table("assessment_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_assessment_components_vocational_course_report_id"),
            ["vocational_course_report_id"],
            unique=False,
        )

    op.create_table(
        "programs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
            name=op.f("fk_programs_campus_id_campuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
        sa.UniqueConstraint("campus_id", "name", name=op.f("uq_programs_campus_id")),
    )
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_programs_campus_id"), ["campus_id"], unique=False)

    op.create_table(
        "source_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("academic_year", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.String(length=36), nullable=True),
        sa.Column("campus_id", sa.String(length=36), nullable=True),
        sa.Column("document_type", sa.String(length=60), nullable=False),
        sa.Column("document_status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision_label", sa.String(length=120), nullable=True),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("detected_years", sa.JSON(), nullable=False),
        sa.Column("year_consistency_status", sa.String(length=30), nullable=False),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_status != 'PUBLISHED' OR (year_consistency_status = 'CONSISTENT' AND verification_status = 'HUMAN_APPROVED')",
            name=op.f("ck_source_documents_published_document_is_verified"),
        ),
        sa.CheckConstraint(
            "document_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_source_documents_document_status_valid"),
        ),
        sa.CheckConstraint(
            "year_consistency_status IN ('CONSISTENT', 'MIXED_YEAR', 'UNKNOWN')",
            name=op.f("ck_source_documents_year_consistency_status_valid"),
        ),
        sa.CheckConstraint(
            "academic_year >= 2000", name=op.f("ck_source_documents_academic_year_valid")
        ),
        sa.CheckConstraint("page_count > 0", name=op.f("ck_source_documents_page_count_positive")),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
            name=op.f("fk_source_documents_campus_id_campuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_source_documents_institution_id_institutions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["source_documents.id"],
            name=op.f("fk_source_documents_supersedes_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_documents")),
        sa.UniqueConstraint("file_hash", name=op.f("uq_source_documents_file_hash")),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_documents_academic_year"), ["academic_year"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_documents_campus_id"), ["campus_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_source_documents_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "vocational_course_statistics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vocational_course_report_id", sa.String(length=36), nullable=False),
        sa.Column("course_mean", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("standard_deviation", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("enrollment_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vocational_course_report_id"],
            ["vocational_course_reports.id"],
            name=op.f(
                "fk_vocational_course_statistics_vocational_course_report_id_vocational_course_reports"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocational_course_statistics")),
        sa.UniqueConstraint(
            "vocational_course_report_id",
            name=op.f("uq_vocational_course_statistics_vocational_course_report_id"),
        ),
    )
    op.create_table(
        "vocational_student_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("vocational_course_report_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=120), nullable=False),
        sa.Column("final_score", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("achievement_level", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vocational_course_report_id"],
            ["vocational_course_reports.id"],
            name=op.f(
                "fk_vocational_student_results_vocational_course_report_id_vocational_course_reports"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocational_student_results")),
        sa.UniqueConstraint(
            "vocational_course_report_id",
            "student_id",
            name=op.f("uq_vocational_student_results_vocational_course_report_id"),
        ),
    )
    with op.batch_alter_table("vocational_student_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vocational_student_results_vocational_course_report_id"),
            ["vocational_course_report_id"],
            unique=False,
        )

    op.create_table(
        "admission_tracks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_round_id", sa.String(length=36), nullable=False),
        sa.Column("program_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admission_round_id"],
            ["admission_rounds.id"],
            name=op.f("fk_admission_tracks_admission_round_id_admission_rounds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.id"],
            name=op.f("fk_admission_tracks_program_id_programs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_tracks")),
        sa.UniqueConstraint(
            "admission_round_id",
            "program_id",
            "code",
            name=op.f("uq_admission_tracks_admission_round_id"),
        ),
    )
    with op.batch_alter_table("admission_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admission_tracks_admission_round_id"),
            ["admission_round_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_admission_tracks_program_id"), ["program_id"], unique=False
        )

    op.create_table(
        "source_document_pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("detected_academic_year", sa.Integer(), nullable=True),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "page_number > 0", name=op.f("ck_source_document_pages_page_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_document_pages_source_document_id_source_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_document_pages")),
        sa.UniqueConstraint(
            "source_document_id",
            "page_number",
            name=op.f("uq_source_document_pages_source_document_id"),
        ),
    )
    with op.batch_alter_table("source_document_pages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_document_pages_source_document_id"),
            ["source_document_id"],
            unique=False,
        )

    op.create_table(
        "source_citations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_page_id", sa.String(length=36), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("locator", sa.String(length=240), nullable=True),
        sa.Column("excerpt_digest", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "page_number > 0", name=op.f("ck_source_citations_page_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
            name=op.f("fk_source_citations_source_document_id_source_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_page_id"],
            ["source_document_pages.id"],
            name=op.f("fk_source_citations_source_document_page_id_source_document_pages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_citations")),
    )
    with op.batch_alter_table("source_citations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_citations_source_document_id"),
            ["source_document_id"],
            unique=False,
        )

    op.create_table(
        "admission_eligibility_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_admission_eligibility_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_admission_eligibility_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_admission_eligibility_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_admission_eligibility_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admission_eligibility_rules")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_admission_eligibility_rules_admission_track_id"),
        ),
    )
    with op.batch_alter_table("admission_eligibility_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admission_eligibility_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "disqualification_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_disqualification_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_disqualification_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_disqualification_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_disqualification_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disqualification_rules")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_disqualification_rules_admission_track_id"),
        ),
    )
    with op.batch_alter_table("disqualification_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_disqualification_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "document_requirements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_document_requirements_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_document_requirements_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_document_requirements_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_document_requirements_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_requirements")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_document_requirements_admission_track_id"),
        ),
    )
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_requirements_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "grade_source_scope_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_grade_source_scope_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_grade_source_scope_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_grade_source_scope_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_grade_source_scope_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_source_scope_rules")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_grade_source_scope_rules_admission_track_id"),
        ),
    )
    with op.batch_alter_table("grade_source_scope_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grade_source_scope_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "multiple_application_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_multiple_application_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_multiple_application_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_multiple_application_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_multiple_application_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_multiple_application_rules")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_multiple_application_rules_admission_track_id"),
        ),
    )
    with op.batch_alter_table("multiple_application_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_multiple_application_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "score_adjustment_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_score_adjustment_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_score_adjustment_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_score_adjustment_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_score_adjustment_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_adjustment_rules")),
        sa.UniqueConstraint(
            "admission_track_id",
            "version",
            name=op.f("uq_score_adjustment_rules_admission_track_id"),
        ),
    )
    with op.batch_alter_table("score_adjustment_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_adjustment_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    op.create_table(
        "score_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_score_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_score_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_score_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_score_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_score_rules")),
        sa.UniqueConstraint(
            "admission_track_id", "version", name=op.f("uq_score_rules_admission_track_id")
        ),
    )
    with op.batch_alter_table("score_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_score_rules_admission_track_id"), ["admission_track_id"], unique=False
        )

    op.create_table(
        "tie_break_rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("admission_track_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("lifecycle_status", sa.String(length=30), nullable=False),
        sa.Column("rule_payload", sa.JSON(), nullable=False),
        sa.Column("source_citation_id", sa.String(length=36), nullable=True),
        sa.Column("independent_verified", sa.Boolean(), nullable=False),
        sa.Column("golden_test_ref", sa.String(length=240), nullable=True),
        sa.Column("human_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_status != 'PUBLISHED' OR (source_citation_id IS NOT NULL AND independent_verified AND golden_test_ref IS NOT NULL AND human_approved_at IS NOT NULL)",
            name=op.f("ck_tie_break_rules_published_rule_has_evidence"),
        ),
        sa.CheckConstraint(
            "lifecycle_status IN ('DRAFT', 'EXTRACTED', 'VERIFIED', 'TESTED', 'HUMAN_APPROVED', 'PUBLISHED', 'SUPERSEDED')",
            name=op.f("ck_tie_break_rules_lifecycle_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["admission_track_id"],
            ["admission_tracks.id"],
            name=op.f("fk_tie_break_rules_admission_track_id_admission_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_citation_id"],
            ["source_citations.id"],
            name=op.f("fk_tie_break_rules_source_citation_id_source_citations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tie_break_rules")),
        sa.UniqueConstraint(
            "admission_track_id", "version", name=op.f("uq_tie_break_rules_admission_track_id")
        ),
    )
    with op.batch_alter_table("tie_break_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tie_break_rules_admission_track_id"),
            ["admission_track_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tie_break_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tie_break_rules_admission_track_id"))

    op.drop_table("tie_break_rules")
    with op.batch_alter_table("score_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_rules_admission_track_id"))

    op.drop_table("score_rules")
    with op.batch_alter_table("score_adjustment_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_adjustment_rules_admission_track_id"))

    op.drop_table("score_adjustment_rules")
    with op.batch_alter_table("multiple_application_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_multiple_application_rules_admission_track_id"))

    op.drop_table("multiple_application_rules")
    with op.batch_alter_table("grade_source_scope_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grade_source_scope_rules_admission_track_id"))

    op.drop_table("grade_source_scope_rules")
    with op.batch_alter_table("document_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_requirements_admission_track_id"))

    op.drop_table("document_requirements")
    with op.batch_alter_table("disqualification_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_disqualification_rules_admission_track_id"))

    op.drop_table("disqualification_rules")
    with op.batch_alter_table("admission_eligibility_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admission_eligibility_rules_admission_track_id"))

    op.drop_table("admission_eligibility_rules")
    with op.batch_alter_table("source_citations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_citations_source_document_id"))

    op.drop_table("source_citations")
    with op.batch_alter_table("source_document_pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_document_pages_source_document_id"))

    op.drop_table("source_document_pages")
    with op.batch_alter_table("admission_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admission_tracks_program_id"))
        batch_op.drop_index(batch_op.f("ix_admission_tracks_admission_round_id"))

    op.drop_table("admission_tracks")
    with op.batch_alter_table("vocational_student_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vocational_student_results_vocational_course_report_id"))

    op.drop_table("vocational_student_results")
    op.drop_table("vocational_course_statistics")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_documents_institution_id"))
        batch_op.drop_index(batch_op.f("ix_source_documents_campus_id"))
        batch_op.drop_index(batch_op.f("ix_source_documents_academic_year"))

    op.drop_table("source_documents")
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programs_campus_id"))

    op.drop_table("programs")
    with op.batch_alter_table("assessment_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assessment_components_vocational_course_report_id"))

    op.drop_table("assessment_components")
    with op.batch_alter_table("vocational_course_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vocational_course_reports_academic_record_id"))

    op.drop_table("vocational_course_reports")
    with op.batch_alter_table("student_course_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_course_records_academic_record_id"))

    op.drop_table("student_course_records")
    with op.batch_alter_table("campuses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campuses_institution_id"))

    op.drop_table("campuses")
    with op.batch_alter_table("admission_rounds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admission_rounds_institution_id"))

    op.drop_table("admission_rounds")
    with op.batch_alter_table("student_academic_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_academic_records_student_id"))

    op.drop_table("student_academic_records")
    with op.batch_alter_table("rule_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_reviews_rule_type"))
        batch_op.drop_index(batch_op.f("ix_rule_reviews_rule_id"))

    op.drop_table("rule_reviews")
    op.drop_table("institutions")
    # ### end Alembic commands ###
