"""Phase 2 확인 입력 저장 계약

Revision ID: 341a80ddba84
Revises: 21b748d3ce27
Create Date: 2026-07-11 14:47:52.537860
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "341a80ddba84"
down_revision: str | None = "21b748d3ce27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("source_format", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("confirmed_row_count", sa.Integer(), nullable=False),
        sa.Column("original_purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_format IN ('csv', 'pasted_table', 'xlsx')",
            name=op.f("ck_import_batches_source_format_valid"),
        ),
        sa.CheckConstraint(
            "status != 'CONFIRMED' OR original_purged_at IS NOT NULL",
            name=op.f("ck_import_batches_confirmed_source_is_purged"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_PURGE', 'CONFIRMED')", name=op.f("ck_import_batches_status_valid")
        ),
        sa.CheckConstraint(
            "char_length(source_hash) = 64", name=op.f("ck_import_batches_source_hash_length")
        ),
        sa.CheckConstraint(
            "confirmed_row_count > 0", name=op.f("ck_import_batches_confirmed_row_count_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_source_hash"), "import_batches", ["source_hash"], unique=False
    )
    op.add_column(
        "student_course_records", sa.Column("import_batch_id", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "student_course_records", sa.Column("raw_score_label", sa.String(length=20), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_student_course_records_raw_score_label_valid"),
        "student_course_records",
        "raw_score_label IS NULL OR raw_score_label = 'P'",
    )
    op.create_check_constraint(
        op.f("ck_student_course_records_raw_score_value_or_label"),
        "student_course_records",
        "raw_score IS NULL OR raw_score_label IS NULL",
    )
    op.create_index(
        op.f("ix_student_course_records_import_batch_id"),
        "student_course_records",
        ["import_batch_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_student_course_records_import_batch_id_import_batches"),
        "student_course_records",
        "import_batches",
        ["import_batch_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_student_course_records_import_batch_id_import_batches"),
        "student_course_records",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_student_course_records_import_batch_id"), table_name="student_course_records"
    )
    op.drop_constraint(
        op.f("ck_student_course_records_raw_score_value_or_label"),
        "student_course_records",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_student_course_records_raw_score_label_valid"),
        "student_course_records",
        type_="check",
    )
    op.drop_column("student_course_records", "raw_score_label")
    op.drop_column("student_course_records", "import_batch_id")
    op.drop_index(op.f("ix_import_batches_source_hash"), table_name="import_batches")
    op.drop_table("import_batches")
    # ### end Alembic commands ###
